### ISSUE TITLE
Locations links

### ISSUE THREAD

**Issue by krebedev** [jonahunuafe/designo-multi-page-website#1]
@jonahunuafe 

Great job on this! Everything is looking good.

Here are two minor changes:

1. On Desktop, in the last section of the homepage, the 'GET IN TOUCH" button seems to be floating on top of the last card titled "FRIENDLY".  The button is entirely missing on mobile view.
2. Locations links: Clicking on a specific location button inside the About or Contact page should not only open the Locations page, but also automatically scroll to the specific location. For example, clicking "Australia" should automatically scroll to the Australia section in the Locations page. One way to achieve this is to assign IDs to each of the locations HTML wrapper elements and reference it in the link using # with the target ID. Remember to set scroll-behavior to smooth on the `body` element so things don't jump around.

**Comment by jonahunuafe** [comment]
1. The GET IN TOUCH button on the home page floated as a result of missing a closing quote on the alt attribute of an img in 
that  section.
2. The links, to the Locations page, when the location button on the About page and Contact page is clicked, has been referenced with their appropriate ID's.  

Thanks for your input in achieving this feat.
